name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2 
        
    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust to match the PHP version used by your Laravel project
        tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
        
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: . # Assuming you want to deploy the entire repo
        server-dir: /home/outofcom/communitychest.app # Deploy to this directory
        
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/outofcom/communitychest.app
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
